package frames

// This is the value stored in the FrameMap
var MyAnimation = DefaultFrameType(myAnimationFrames)

var myAnimationFrames = []string{
  `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kxolc:;;,,,,,;:clodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0dc,..                    ..;cx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc'.                              .;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd'                                     .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNd'                                         'xWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMK:                                            .dWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMK;                 ..;:cccc;'.                  .OMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXc                ,d0NWMMMMMWN0d,                 cNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWx.              .xNMMMMMMMMMMMMMXc                '0MMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNc              .kWMMMMMMMMMMMMMMM0,               .kMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMW0o:;;,'....   .oNMMMMMMMMMMMMMMMMNc               .kMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXK00OOKWMMMMMMMMMMMMMMMMMNl               .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNc               .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Oxxdoolcc:;,.               .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkdl:;'..                             .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:'.                                     .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,.                                         .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMW0c.                       .....                .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMXl.                 .':ldxkO0KKX0:               .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM0;                .;xKNWMMMMMMMMMNc               .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM0,                ;OWMMMMMMMMMMMMMNc               .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXc                :KMMMMMMMMMMMMMMMNc               .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMk.               .OMMMMMMMMMMMMMMMMK;               .xMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWl                ;KMMMMMMMMMMMMMMMMk.               .dWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMN:                ,KMMMMMMMMMMMMMMMK;                 cNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNc                .kWMMMMMMMMMMMMMK:                  .xWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWl                 ,OWMMMMMMMMMMNx'                    .dNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMk.                 .lOXNWWNXKOo,                       .cKMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMX:                    .',,'..                            ,0MMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM0,                                                      ,0MMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM0;                                .cxl.              ,dXMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMXo.                            .l0WMWk,          .:kNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWKd,.                      .:xXWMMMMMXo.      .l0WMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMWMMMMMMMMMMMMMMMMMMMMMMN0dc,..         ...,cloOXWMMMMMMMMMWKo,..,dXWMMMMMMMWWNNNXXXXNNWWMMMMMM
MMMMMNK0KNWMMMMMMMMMMMMMMMMMMMMMMWXK0OkxxxkkO0KNWMMMMMMMMMMMMMMMMMMNKKNMMMMMMWNK0OOkkkkkkkkkOKNMMMMM
MMMMMWX0kkOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0KKKKKKKK0OkxxOXMMMMM
MMMMMMMWX0kxkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMWXOxxONMMMMM
MMMMMMMMMWX0kxxkkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0KNMMWKkxkKWMMMMM
MMMMMMMMMMMWNKOkxxxkkOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKKOkkkkKWMMN0xk0NMMMMMM
MMMMMMMMMMMMMWNX0OkxxxxkkO0KXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK0OkkxxxkOKNWMMWKkk0NMMMMMMM
MMMMMMMMMMMMMMMMWNK0OkxxxxxxxkkO00KXXNNWWWWWMMMMMMMMMMMWWWWWNNNXXK00OkkkxxxxxkO0XNWMMMWXOk0NMMMMMMMM
MMMMMMMMMMMMMMMMMMMWNX0OkxxxxxxxxxxxkkkOOO0000KKKKKKK0000OOOOkkkxxxxxxxxxxkO0XNWMMMMMMWK0XWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWWXK0OkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkO0KXWWMMMMMMMMMWWWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0OkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXK00OOOkkkkkkkkkkkkkkkOO000KXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNXXXXXXXXXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`,
}
